# Generated by Django 4.1.7 on 2023-03-15 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useaccounts', '0002_student_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
